# Site settings
title: Wdy Blog
SEOTitle: 码路芽子的博客 | Wdy Blog
header-img: img/post-bg-desk.jpg
email: mlyz.wdy@qq.com
description: "码路芽子的个人网站"
keyword: " Wdy, Wdy Blog, 码路芽子, 码路芽子的博客, wangdongyao, dongyao, wdy,  王冬尧, iOS, Apple, iPhone, web, FD, 前端, H5, 小程序"
url: "http://mlyz-wdy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mlyz-wdy/mlyz-wdy.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "思想和行动，总有一个要在路上!"
sidebar-avatar: /img/avatar.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username:    mlyz-wdy
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: mlyz

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1a01cb608b947505a308                            #生成的clientID
  clientSecret: cde31b5120f3b5e300d200311aa724ef0f5e1533    #生成的clientSecret
  repo: mlyz-wdy.github.io    #仓库名称
  owner: mlyz-wdy    #github用户名
  admin: mlyz
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: cabbbadf0b31b0df0079d34a5abfdbf9

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "掘金.Wdy",
        href: "https://juejin.im/user/712139265545277"
    }
]
